sudo: required
services:
  - docker

before_install:
  - docker build -t eyangondjip/docker-react -f Dockerfile.dev .

script:
  - docker run eyangondjip/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-us-east-1-866012544765"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
